import fs from 'node:fs/promises';
import { SpreadsheetFile, Workbook } from '@oai/artifact-tool';
const root='/Users/janakirampulipati/ibd-research-review';
const data=JSON.parse(await fs.readFile(`${root}/prototype_work/prototype-data.json`,'utf8'));
const wb=Workbook.create();
const colors={navy:'#17324D',blue:'#2E6882',pale:'#EAF3F4',yellow:'#FFF2B2',red:'#F8D7DA',amber:'#FCE5B3',green:'#DDEFE2',ink:'#1F2937',white:'#FFFFFF'};
const letters=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s};
const val=v=>v==null?'':Array.isArray(v)?v.join('; '):v;
function add(name,title,subtitle,headers,rows,opts={}){const sh=wb.worksheets.add(name);sh.showGridLines=false;const last=letters(headers.length);sh.getRange(`A1:${last}1`).merge();sh.getRange('A1').values=[[title]];sh.getRange(`A2:${last}2`).merge();sh.getRange('A2').values=[[subtitle]];sh.getRange(`A1:${last}1`).format={fill:colors.navy,font:{bold:true,color:colors.white,size:15},verticalAlignment:'center'};sh.getRange(`A2:${last}2`).format={fill:colors.pale,font:{italic:true,color:colors.ink,size:10},wrapText:true,verticalAlignment:'center'};sh.getRange('A1').format.rowHeight=30;sh.getRange('A2').format.rowHeight=42;sh.getRange(`A4:${last}4`).values=[headers];sh.getRange(`A4:${last}4`).format={fill:colors.blue,font:{bold:true,color:colors.white,size:10},wrapText:true,verticalAlignment:'center'};sh.getRange(`A4:${last}4`).format.rowHeight=38;const end=4+rows.length;if(rows.length){sh.getRange(`A5:${last}${end}`).values=rows.map(r=>headers.map(h=>val(r[h])));sh.getRange(`A5:${last}${end}`).format={font:{color:colors.ink,size:9},wrapText:true,verticalAlignment:'top',borders:{insideHorizontal:{style:'thin',color:'#D6DEE5'}}};sh.getRange(`A5:${last}${end}`).format.rowHeight=opts.rowHeight||70;const t=sh.tables.add(`A4:${last}${end}`,true,`${name.replace(/[^A-Za-z0-9]/g,'')}Table`);t.style='TableStyleMedium2';t.showFilterButton=true;t.showBandedRows=true;if(opts.human){for(const h of opts.human){const i=headers.indexOf(h);if(i>=0)sh.getRange(`${letters(i+1)}5:${letters(i+1)}${end}`).format.fill=colors.yellow;}}if(opts.dropdown){for(const h of opts.dropdown){const i=headers.indexOf(h);if(i>=0)sh.getRange(`${letters(i+1)}5:${letters(i+1)}${end}`).dataValidation={rule:{type:'list',values:opts.dropdownValues}};}}}headers.forEach((h,i)=>sh.getRange(`${letters(i+1)}:${letters(i+1)}`).format.columnWidth=opts.widths?.[i]||22);sh.freezePanes.freezeRows(4);return sh;}
const claimHeaders=['claimId','sourceId','sourceTitle','sourceUrl','conditionApplicability','diseaseContext','topic','outcomeType','claimText','plainLanguageExplanation','supportingExcerpt','exactLocator','evidenceLevel','limitations','applicabilityLimitations','confidence','prototypeEligibilityStatus','userDecision','reviewerNotes'];
const sourceHeaders=['sourceId','sourceTitle','sourceUrl','publicationYear','sourceType','conditionApplicability','diseaseContext','evidenceLimitations','canadaUsApplicability','regionalAssessment','reviewStatus','userDecision','userNotes'];
const decisions=['Approve for prototype','Reject','Needs more evidence'];
add('Included Sources','Included sources','Only active sources referenced by included claims. Human review fields are blank.',sourceHeaders,data.sources,{human:['userDecision','userNotes'],dropdown:['userDecision'],dropdownValues:decisions,rowHeight:82,widths:[12,44,48,12,16,26,26,44,24,44,20,24,34]});
add('Included Claims','Included claims','Prototype-eligible claims after conservative filtering. No claim is approved.',claimHeaders,data.claims,{human:['userDecision','reviewerNotes'],dropdown:['userDecision'],dropdownValues:['Approve for prototype','Reject','Approve with limitation','Needs more evidence'],rowHeight:92,widths:[12,12,40,42,24,25,20,24,56,56,58,48,20,44,44,14,28,26,34]});
add('Included With Limitations','Included with limitations','Claims retained with visible caveats that must remain attached.',claimHeaders,data.claims.filter(x=>x.prototypeEligibilityStatus==='prototype_eligible_with_limitation'),{human:['userDecision','reviewerNotes'],dropdown:['userDecision'],dropdownValues:['Approve for prototype','Reject','Approve with limitation','Needs more evidence'],rowHeight:100,widths:[12,12,40,42,24,25,20,24,56,56,58,48,20,44,44,14,28,26,34]});
const excludedRows=data.excluded.filter(x=>String(x.result).startsWith('excluded_'));
add('Excluded Claims','Excluded claims','Excluded from prototype and approved-data export; reasons are explicit.', ['claimId','result','reason','reviewStatus','userDecision','reviewerNotes'], excludedRows,{human:['userDecision','reviewerNotes'],dropdown:['userDecision'],dropdownValues:['Approve for prototype','Reject','Needs more evidence'],rowHeight:78,widths:[14,34,70,22,26,34]});
add('CLM-083 Correction','CLM-083 correction','Narrowed to the directly supported disease scope and retained EL5 caveats.', ['claimId','previousScope','correctedScope','sourcePassage','exactLocator','correctionReason','userDecision','reviewerNotes'], [{claimId:'CLM-083',previousScope:'ulcerative_colitis; crohns_disease; ibd_general',correctedScope:'crohns_disease — stricturing disease with obstructive symptoms',sourcePassage:'Statement 21.1: While there are no data supporting a modified or low-fiber diet to manage stricturing Crohn’s disease (CD), mechanism-based reasoning suggests that a diet low in bulking fiber in people with stricturing CD and obstructive symptoms might reduce the risk of developing intestinal obstruction. (EL5)',exactLocator:'Official ECCO consensus article — Section 4.3.2, “Strictures”; Statement 21.1, paragraph 1',correctionReason:'UC and general IBD tags were unsupported; outcome/confidence now reflect obstruction risk and EL5 mechanism-based reasoning.',userDecision:'',reviewerNotes:''}],{human:['userDecision','reviewerNotes'],dropdown:['userDecision'],dropdownValues:['Approve for prototype','Reject','Approve with limitation','Needs more evidence'],rowHeight:110,widths:[14,34,38,76,50,60,26,34]});
add('CLM-096-100 Metadata','CLM-096–100 metadata completion','Completed required prototype metadata from active 2023 ESPEN source SRC-026; superseded 2017 source is not referenced.', ['claimId','sourceId','sourceTitle','sourceUrl','publicationYear','evidenceLevel','conditionApplicability','diseaseContext','outcomeType','studyType','limitations','applicabilityLimitations','confidence','exactLocator','prototypeEligibilityStatus','userDecision','reviewerNotes'], data.claims.filter(x=>/^CLM-09[6-9]|CLM-100$/.test(x.claimId)).map(x=>({...x,userDecision:'',reviewerNotes:''})),{human:['userDecision','reviewerNotes'],dropdown:['userDecision'],dropdownValues:['Approve for prototype','Reject','Approve with limitation','Needs more evidence'],rowHeight:96,widths:[12,12,42,46,12,20,25,25,28,24,44,46,14,58,30,26,34]});
const cov=['ulcerative_colitis','crohns_disease','ibd_general','active_disease','remission','food','nutrition','lifestyle','symptoms','inflammation','evidence_uncertainty'];
const coverageRows=cov.map(k=>({area:k,claimCount:data.claims.filter(c=>JSON.stringify(c).toLowerCase().includes(k)).length,assessment:['lifestyle','symptoms'].includes(k)?'limited / not a standalone supported area':k==='inflammation'?'partial and source-specific':'present in included records'}));
add('Prototype Coverage','Prototype coverage','Coverage is record-tag coverage, not a claim of clinical completeness.', ['area','claimCount','assessment'],coverageRows,{rowHeight:40,widths:[28,16,72]});
const summaryRows=[{metric:'Total active claims reviewed',value:61,detail:'Authoritative QA count'},{metric:'Claims included',value:data.claims.length,detail:'Prototype-eligible'},{metric:'Included with limitation',value:data.claims.filter(x=>x.prototypeEligibilityStatus==='prototype_eligible_with_limitation').length,detail:'Visible caveat required'},{metric:'Claims excluded',value:excludedRows.length,detail:'Not in prototype export'},{metric:'Prototype source count',value:data.sources.length,detail:'Active sources only'},{metric:'CLM-092',value:'Excluded',detail:'still_needs_evidence; no further research'},{metric:'Human approval',value:'None',detail:'All reviewer fields blank'}];
add('Prototype Summary','Prototype evidence summary','Informational prototype only. Stop for human review; no approvals are recorded.', ['metric','value','detail'],summaryRows,{rowHeight:48,widths:[36,22,78]});
await fs.mkdir(`${root}/previews-prototype`,{recursive:true});
for(const sh of wb.worksheets.items){const blob=await wb.render({sheetName:sh.name,autoCrop:'all',scale:1,format:'png'});await fs.writeFile(`${root}/previews-prototype/${sh.name.replace(/[^A-Za-z0-9]+/g,'-').toLowerCase()}.png`,new Uint8Array(await blob.arrayBuffer()));}
const out=await SpreadsheetFile.exportXlsx(wb);await out.save(`${root}/ibd-prototype-evidence-review.xlsx`);
console.log(JSON.stringify({sheets:wb.worksheets.items.map(s=>s.name),claims:data.claims.length,sources:data.sources.length},null,2));
