import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path('/Users/janakirampulipati/ibd-research-review')
base = json.loads((ROOT / 'ibd-prototype-evidence.json').read_text())

new_sources = [
    {'sourceId':'SRC-027','sourceTitle':'ACG Clinical Guideline Update: Ulcerative Colitis in Adults','sourceUrl':'https://gi.org/journals-publications/ebgi/alkazzi_aug2025/','publicationYear':2025,'sourceType':'clinical guideline summary','conditionApplicability':'ulcerative_colitis','diseaseContext':'active_disease; remission; suspected_relapse; maintenance','evidenceLimitations':'Official ACG summary of the 2025 guideline; the journal article is cited by DOI but full guideline text may be access-restricted. Recommendations include GRADE certainty levels; individual treatment choice requires clinician assessment.','canadaUsApplicability':'portable_with_qualification','regionalAssessment':'US professional guideline; scientific content is relevant to Canada, but approvals, formularies, and care pathways require local review.','reviewStatus':''},
    {'sourceId':'SRC-028','sourceTitle':'AGA Clinical Practice Guideline on the Role of Biomarkers for the Management of Ulcerative Colitis','sourceUrl':'https://pubmed.ncbi.nlm.nih.gov/36822736/','publicationYear':2023,'sourceType':'clinical guideline','conditionApplicability':'ulcerative_colitis','diseaseContext':'symptomatic_remission; active_disease; suspected_relapse','evidenceLimitations':'PubMed abstract and official AGA guidance are publicly accessible; full journal article and evidence tables may be access-restricted. Recommendations are conditional and threshold use is not a diagnosis.','canadaUsApplicability':'portable_with_qualification','regionalAssessment':'US guideline; laboratory assay performance and access should be checked locally.','reviewStatus':''},
    {'sourceId':'SRC-029','sourceTitle':'Intestinal ultrasound for monitoring therapeutic response in patients with ulcerative colitis: results from the TRUST&UC study','sourceUrl':'https://pubmed.ncbi.nlm.nih.gov/31862811/','publicationYear':2020,'sourceType':'prospective observational study','conditionApplicability':'ulcerative_colitis','diseaseContext':'active_disease; treatment_response; monitoring','evidenceLimitations':'Prospective observational study in 42 German IBD centres; no randomized comparator. Authors state predictive potential requires future verification. CC BY-NC; no commercial reuse.','canadaUsApplicability':'portable_with_qualification','regionalAssessment':'Monitoring findings are broadly relevant; operator expertise, equipment, and local pathways vary.','reviewStatus':''},
    {'sourceId':'SRC-030','sourceTitle':'Correlations Between Gastrointestinal Symptoms and Endoscopic-Histologic Disease Activity in Adults with Ulcerative Colitis','sourceUrl':'https://pubmed.ncbi.nlm.nih.gov/37268795/','publicationYear':2023,'sourceType':'secondary analysis of prospective cohort','conditionApplicability':'ulcerative_colitis','diseaseContext':'remission; active_disease; symptoms_vs_inflammation','evidenceLimitations':'Secondary analysis from one tertiary referral centre; 254 colonoscopies from 179 adults; symptom and objective activity associations do not diagnose an individual.','canadaUsApplicability':'portable_with_qualification','regionalAssessment':'UC symptom/objective discordance is clinically relevant; local assessment standards still apply.','reviewStatus':''},
    {'sourceId':'SRC-031','sourceTitle':'U-ACHIEVE Maintenance: efficacy and safety of upadacitinib maintenance therapy in moderately to severely active ulcerative colitis','sourceUrl':'https://pubmed.ncbi.nlm.nih.gov/37683686/','publicationYear':2023,'sourceType':'randomized placebo-controlled phase 3 maintenance trial','conditionApplicability':'ulcerative_colitis','diseaseContext':'moderate_to_severe_active_disease; maintenance_remission','evidenceLimitations':'Only induction responders were re-randomized for maintenance; sponsored trial; efficacy percentages are population-level and not individualized treatment advice.','canadaUsApplicability':'portable_with_qualification','regionalAssessment':'Trial evidence is broadly relevant; regulatory status, safety warnings, and access require local review.','reviewStatus':''},
    {'sourceId':'SRC-032','sourceTitle':'Exposure-Response Characterization of Tofacitinib Efficacy in Moderate to Severe Ulcerative Colitis','sourceUrl':'https://pubmed.ncbi.nlm.nih.gov/35380740/','publicationYear':2022,'sourceType':'exposure-response analysis of phase 2/3 trials','conditionApplicability':'ulcerative_colitis','diseaseContext':'moderate_to_severe_active_disease; maintenance_remission','evidenceLimitations':'Post hoc exposure-response modelling of OCTAVE trials; estimates depend on model assumptions and trial populations. Not a prescribing recommendation.','canadaUsApplicability':'portable_with_qualification','regionalAssessment':'Scientific findings are broadly relevant; dosing and safety must follow local product information.','reviewStatus':''},
]

def claim(cid, sid, topic, outcome, context, text, excerpt, locator, level, limitations, app='UC-specific evidence; not individualized diagnosis or treatment advice.', confidence='moderate', eligibility='prototype_eligible'):
    src = next(s for s in new_sources if s['sourceId'] == sid)
    return {'claimId':cid,'sourceId':sid,'sourceTitle':src['sourceTitle'],'sourceUrl':src['sourceUrl'],'conditionApplicability':'ulcerative_colitis','diseaseContext':context,'topic':topic,'outcomeType':outcome,'claimText':text,'plainLanguageExplanation':text,'supportingExcerpt':excerpt,'exactLocator':locator,'evidenceLevel':level,'limitations':limitations,'applicabilityLimitations':app,'confidence':confidence,'prototypeEligibilityStatus':eligibility}

new_claims = [
 claim('CLM-101','SRC-028','fecal_calprotectin; CRP','biomarker_monitoring','symptomatic_remission; active_disease','The AGA recommends combining symptoms with biomarkers rather than symptoms alone when monitoring ulcerative colitis.','In patients with UC in symptomatic remission, the panel suggests the use of a biomarker- and symptom-based monitoring strategy over a symptom-based monitoring strategy.','PubMed abstract — Results paragraph; recommendation 1','conditional guideline recommendation','Conditional recommendations; biomarkers inform monitoring but do not replace clinical assessment.'),
 claim('CLM-102','SRC-028','fecal_calprotectin; CRP','rule_out_active_inflammation','symptomatic_remission','In symptomatic remission, fecal calprotectin below 150 μg/g or normal CRP can help rule out active inflammation and avoid routine endoscopic assessment, according to the AGA guideline.','For patients in symptomatic remission, the panel suggests using fecal calprotectin <150 μg/g, normal fecal lactoferrin, and/or normal CRP to rule out active inflammation and avoid routine endoscopic assessment of disease.','PubMed abstract — Results paragraph; recommendation 2','conditional guideline recommendation','Thresholds are guideline decision aids, not diagnostic cutoffs for an individual.'),
 claim('CLM-103','SRC-028','fecal_calprotectin; CRP','endoscopic_assessment','symptomatic_remission; suspected_relapse','When a patient with UC is in symptomatic remission but biomarkers are elevated, the AGA suggests endoscopic assessment rather than empiric treatment adjustment.','In patients in symptomatic remission but elevated biomarkers ... the panel suggests endoscopic assessment of disease to inform treatment decisions.','PubMed abstract — Results paragraph','conditional guideline recommendation','Do not infer a flare or change medication from biomarkers alone.'),
 claim('CLM-104','SRC-027','fecal_calprotectin; CRP','monitoring_response_relapse','active_disease; maintenance; suspected_relapse','The 2025 ACG UC guideline recommends fecal calprotectin to assess response to therapy, evaluate suspected relapse, and monitor during maintenance.','We recommend the use of FC in UC to assess response to therapy, to evaluate suspected relapse, and during maintenance (Strong recommendation, moderate quality evidence).','Official ACG guideline summary — Table 1, recommendation 5, lines 243–245','strong guideline recommendation','The recommendation concerns monitoring, not self-interpretation or treatment changes.'),
 claim('CLM-105','SRC-027','mucosal_healing','endoscopic_improvement','active_disease; remission','The 2025 ACG UC guideline recommends treating to endoscopic improvement, defined as resolution of inflammatory changes (Mayo Endoscopic Score 0 or 1), to increase the likelihood of sustained steroid-free remission and prevent hospitalization and surgery.','We recommend treating patients with UC to achieve endoscopic improvement (defined as resolution of inflammatory changes [MES 0 or 1]) to increase the likelihood of sustained steroid-free remission and to prevent hospitalizations and surgery.','Official ACG guideline summary — Table 1, recommendation 4, lines 238–245','strong guideline recommendation','Endoscopic targets require clinician-performed assessment; this is not a promise of outcome.'),
 claim('CLM-106','SRC-027','colonoscopy; intestinal_ultrasound; monitoring','objective_monitoring','active_disease; maintenance; suspected_relapse','The 2025 ACG UC guideline lists fecal calprotectin, CRP, flexible sigmoidoscopy or colonoscopy, and/or intestinal ultrasound as ways to assess and monitor UC response, maintenance, and suspected relapse.','Disease assessment and monitoring in response to therapy and during maintenance and periods of suspected relapse may be performed with FC, CRP, endoscopic assessment with flexible sigmoidoscopy or colonoscopy, and/or intestinal ultrasound.','Official ACG guideline summary — Table 2, key concept 8, lines 313–315','guideline key concept','Choice and timing depend on clinical context, resources, and clinician judgment.'),
 claim('CLM-107','SRC-027','symptoms_vs_inflammation; mucosal_healing','symptom_and_endoscopic_remission','remission; active_disease','The ACG distinguishes symptomatic remission from endoscopic healing and describes deep remission as both; symptoms alone should not be treated as equivalent to healed mucosa.','Symptomatic remission relates to improvement in PROs while endoscopic healing is defined as restoration of intact mucosa without friability. Deep remission is a combination of symptomatic remission and endoscopic healing.','Official ACG guideline summary — Table 2, key concept 11, lines 316–319','guideline key concept','Definitions support clinical communication; they do not establish an individual’s inflammatory state without assessment.'),
 claim('CLM-108','SRC-029','intestinal_ultrasound','short_term_treatment_response','active_disease; treatment_response','In the prospective TRUST&UC study of UC patients in clinical relapse across 42 German IBD centres, bowel-wall thickness decreased during treatment and normalization at 12 weeks correlated with symptomatic response; the authors said predictive value needs future verification.','At baseline, 88.5% (n=224) had increased bowel wall thickness; normalization of BWT and clinical response after 12 weeks showed a high correlation ... The potential to predict therapeutic response requires future verification.','PubMed abstract — Results and Conclusions, lines 252–257','prospective observational study','Association in an observational study; IUS is operator- and setting-dependent and does not replace clinical assessment.'),
 claim('CLM-109','SRC-030','symptoms_vs_inflammation','symptom_objective_discordance','remission; active_disease','In a secondary analysis of 254 colonoscopies from 179 adults with UC, 28% were in endo-histologic remission and 25% of those still reported GI symptoms; symptoms and objective inflammation were related but not interchangeable.','One-quarter (28%, 72/254) of cases were in endo-histologic remission; of these, 25% (18/72) report GI symptoms ... specificity of endo/histologic inflammation for GI symptoms was <65%.','PubMed abstract — Methods and Results','secondary analysis of prospective cohort','Single tertiary-centre cohort; symptom persistence does not prove active inflammation or its absence.'),
 claim('CLM-110','SRC-027','biologics','maintenance_remission','moderate_to_severe_active_disease; maintenance_remission','The 2025 ACG guideline recommends continuing effective advanced therapies, including anti-TNF agents, vedolizumab, ustekinumab, IL-23 agents, and S1P modulators, for maintenance of remission in appropriate UC responders.','Recommendations 38–42: continue S1P modulators, ustekinumab, IL-23 agents, vedolizumab, and anti-TNF therapy for maintenance of remission after response.','Official ACG guideline summary — Table 1, recommendations 38–42, lines 280–290','strong guideline recommendations','Class-level summary; individual drug selection, contraindications, and monitoring require clinician review.'),
 claim('CLM-111','SRC-027','biologics; loss_of_response','therapeutic_drug_monitoring','moderate_to_severe_active_disease; loss_of_response','For UC patients responding to anti-TNF therapy who are losing response, the 2025 ACG guideline suggests measuring serum drug levels and antidrug antibodies when insufficient drug exposure is suspected.','In patients with moderately to severely active UC who are responders to anti-TNF therapy and now losing response, we suggest measuring serum drug levels and antidrug antibodies ...','Official ACG guideline summary — Table 1, recommendation 44, lines 291–293','conditional guideline recommendation','Very low certainty; testing and interpretation are clinician-led and should not trigger self-directed medication changes.'),
 claim('CLM-112','SRC-027','JAK_inhibitors','induction_and_maintenance_remission','moderate_to_severe_active_disease; maintenance_remission','The 2025 ACG guideline recommends tofacitinib and upadacitinib for induction of remission in moderately to severely active UC and recommends continuing them for maintenance in patients who achieved remission after induction.','Recommendations 30–31 recommend tofacitinib and upadacitinib for induction; recommendation 43 recommends continuing either for maintenance after induction response.','Official ACG guideline summary — Table 1, recommendations 30–31 and 43, lines 266–290','strong guideline recommendations','Treatment decisions require clinician assessment of risks, contraindications, and regulatory labeling.'),
 claim('CLM-113','SRC-031','JAK_inhibitors','maintenance_clinical_remission','moderate_to_severe_active_disease; maintenance_remission','In the phase 3 U-ACHIEVE maintenance trial, among 681 UC induction responders re-randomized for 52 weeks, clinical remission at week 52 was 40.4% with upadacitinib 15 mg, 53.6% with 30 mg, and 10.8% with placebo.','PubMed abstract — Methods and Findings; 681 re-randomized patients; week-52 clinical remission results','phase 3 randomized placebo-controlled maintenance trial','Only induction responders were randomized; sponsored trial; rates are population-level and not individualized predictions.'),
 claim('CLM-114','SRC-032','JAK_inhibitors','maintenance_remission','moderate_to_severe_active_disease; maintenance_remission','An exposure-response analysis of OCTAVE trials reported model-estimated week-52 maintenance remission rates of 29% and 41% for tofacitinib 5 mg and 10 mg twice daily among patients in remission after induction, with estimates depending on model assumptions.','Estimates to achieve/maintain remission at week 52 of maintenance were 29% and 41% for tofacitinib 5 mg and 10 mg twice daily, respectively, in patients in remission following induction.','PubMed abstract — Results; OCTAVE Induction and OCTAVE Sustain populations','post hoc exposure-response analysis','Model-based estimates from trial data; not a prescribing recommendation and not a guarantee for an individual.'),
]

uc_existing = [x for x in base['claims'] if x.get('conditionApplicability') != 'crohns_disease']
crohn_only = [x['claimId'] for x in base['claims'] if x.get('conditionApplicability') == 'crohns_disease']
updated_claims = uc_existing + new_claims
used_sources = {x['sourceId'] for x in updated_claims}
updated_sources = [s for s in base['sources'] + new_sources if s['sourceId'] in used_sources]
excluded = sorted(set(base['excludedClaimIds']) | set(crohn_only))
updated = {'version':'uc-prototype-v2','createdAt':datetime.now(timezone.utc).isoformat(),'intendedUse':'informational UC evidence prototype only','sources':updated_sources,'claims':updated_claims,'excludedClaimIds':excluded,'limitations':['Human review and approval fields remain blank; no source or claim is approved.','The 15 Crohn’s-only claims from the prior prototype remain excluded from UC retrieval.','ESR remains an unresolved UC-specific evidence gap in this bounded run; no IBD-general or Crohn’s-only ESR claim was relabeled as UC evidence.','Guideline recommendations and trial results are informational, not diagnosis, flare prediction, or individualized treatment advice.','Some guideline articles are represented by public official summaries or PubMed abstracts; full text, licensing, and local Canada/US implementation require review.']}
(ROOT/'ibd-uc-evidence-prototype-v2.json').write_text(json.dumps(updated,indent=2,ensure_ascii=False)+'\n')

areas=['fecal_calprotectin','crp','esr','mucosal_healing','colonoscopy','intestinal_ultrasound','biologics','jak_inhibitors','symptoms_vs_inflammation']
def area_counts(claims):
    return {a:sum(1 for x in claims if a in (str(x.get('topic'))+';'+str(x.get('outcomeType'))+';'+str(x.get('diseaseContext'))).lower()) for a in areas}
before=area_counts(uc_existing); after=area_counts(updated_claims)
summary={'version':'uc-prototype-v2','activeSources':len(updated_sources),'includedClaims':len(updated_claims),'excludedClaims':len(excluded),'priorUcEligibleClaims':len(uc_existing),'newUcClaims':len(new_claims),'priorCrohnOnlyExclusions':len(crohn_only),'coverageBefore':before,'coverageAfter':after,'unresolvedGaps':['ESR'],'tests':'pending'}
(ROOT/'uc-evidence-summary-v2.json').write_text(json.dumps(summary,indent=2)+'\n')
(ROOT/'uc-evidence-exclusions-v2.json').write_text(json.dumps({'version':'uc-prototype-v2','excludedClaimIds':excluded,'priorCrohnOnlyExcludedClaimIds':sorted(crohn_only),'reason':'Crohn’s-only claims are retained in the audit boundary and excluded from UC retrieval; prior prototype exclusions remain excluded.','esrStatus':'unresolved_not_relabelled'},indent=2)+'\n')
report=f'''# UC evidence companion extension — v2\n\nAdded {len(new_claims)} UC-specific claims from six bounded public sources and preserved the existing {len(crohn_only)} Crohn’s-only retrieval exclusions. No human approvals were recorded.\n\n- Prior prototype: 20 sources, 49 claims\n- Updated UC export: {len(updated_sources)} active sources, {len(updated_claims)} UC-eligible claims\n- New UC claims: {len(new_claims)}\n- Crohn’s-only claims retained as exclusions: {len(crohn_only)}\n- Prior excluded IDs retained: {len(base['excludedClaimIds'])}\n\n## Coverage before and after\n\n{json.dumps({'before':before,'after':after},indent=2)}\n\nCoverage counts are tagged claims, not clinical completeness.\n\n## Unresolved gaps\n\n- ESR remains unresolved as a UC-specific claim. No general IBD or Crohn’s-only evidence was upgraded to UC-specific evidence.\n- Some guideline evidence is represented by public summaries or abstracts; full text and licensing require human review.\n- Canada/US regulatory, formulary, and local-care applicability remains to be checked.\n- No diagnosis, flare prediction, personalized treatment, or RAG/application implementation was performed.\n\nAll sources and claims remain pending human review.\n'''
(ROOT/'uc-evidence-extension-report.md').write_text(report)
print(json.dumps({'sources':len(updated_sources),'claims':len(updated_claims),'newClaims':len(new_claims),'crohnOnlyExcluded':len(crohn_only),'coverageAfter':after},indent=2))
