from __future__ import annotations

from uc_evidence_discovery import config
from uc_evidence_discovery.runner import main


def test_no_write_to_prototype_evidence_or_db_or_vercel(state_root):
    prototype = config.REPO_ROOT / "apps" / "ibd-uc-rag-agent-web" / "api" / "data" / "ibd-prototype-evidence.json"
    vercel_dir = config.REPO_ROOT / "apps" / "ibd-uc-rag-agent-web" / ".vercel"
    # stable, non-generated db/ subtrees only (db/reports/*.md can be regenerated by an
    # unrelated local pipeline.reconcile process and must not make this test flaky)
    migrations_dir = config.REPO_ROOT / "db" / "supabase" / "migrations"
    pipeline_dir = config.REPO_ROOT / "db" / "pipeline"

    def _mtimes(d):
        return sorted(p.stat().st_mtime for p in d.rglob("*.py")) + \
               sorted(p.stat().st_mtime for p in d.rglob("*.sql")) if d.exists() else []

    before = {
        "prototype": prototype.stat().st_mtime if prototype.exists() else None,
        "vercel_exists": vercel_dir.exists(),
        "migrations": _mtimes(migrations_dir),
        "pipeline": _mtimes(pipeline_dir),
    }

    rc = main(["--state-root", str(state_root), "--dry-run", "--no-network"])
    assert rc == 0

    assert (prototype.stat().st_mtime if prototype.exists() else None) == before["prototype"]
    assert vercel_dir.exists() == before["vercel_exists"]
    assert _mtimes(migrations_dir) == before["migrations"]
    assert _mtimes(pipeline_dir) == before["pipeline"]


def test_manifest_target_index_is_none_when_a_source_is_merged(state_paths, tmp_path):
    from uc_evidence_discovery import package

    package.merge(
        state_paths, run_id="uc-exp-000000000001",
        accepted=[{
            "record": {"doi": "10.1/x", "pmid": "1"},
            "sourceRecord": {"sourceId": "SRC-100", "title": "t", "doi": "10.1/x", "pubmedId": "1",
                             "canonicalUrl": "", "ucApplicability": "ulcerative_colitis",
                             "archivalStatus": "link_only", "redistributionStatus": "not_established",
                             "licence": "", "humanReviewStatus": "", "clinicalReviewStatus": "",
                             "reviewerNotes": ""},
            "claims": [],
        }],
        licensing_entries=[],
    )
    import json

    manifest = json.loads(state_paths.manifest_path.read_text("utf-8"))
    assert "NONE" in manifest["targetIndex"]
    assert manifest["productionPromotion"] == "blocked_by_design"


def test_runner_has_no_supabase_or_deploy_or_vercel_hooks():
    """The doNot list in nextRecommendedOperation legitimately *mentions* Supabase in prose
    ("don't promote to ... or Supabase") -- that is documentation, not a hook. What must never
    appear anywhere under automation/ is an actual integration: a DB driver import, a
    connection-string env var, or a vercel/supabase CLI invocation."""
    banned_imports = ("psycopg", "psycopg2", "supabase")
    banned_tokens = ("DATABASE_URL", "VERCEL_TOKEN", "vercel deploy", "supabase db push",
                     "supabase.co")
    this_file = config.AUTOMATION_DIR / "tests" / "test_no_promotion.py"
    for py_file in config.AUTOMATION_DIR.rglob("*.py"):
        if ".venv" in py_file.parts or "__pycache__" in py_file.parts or py_file == this_file:
            continue
        text = py_file.read_text("utf-8", errors="ignore")
        for bad in banned_imports:
            assert f"import {bad}" not in text and f"from {bad}" not in text, (py_file, bad)
        for bad in banned_tokens:
            assert bad not in text, (py_file, bad)
